version: '3'
services:
  postgres:
    restart: always
    image: mdillon/postgis:9.6-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
